<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;


/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     * Nous donne le nombre de son(s) reliés au son visualisé
//     *
//     * @return mixed float | null
//     */
//    public function getNumberTracks()    // int $id)
//    {
//        $qb = $this->createQueryBuilder('t');
//
//        return $qb
//            ->select('COUNT(*) FROM `track`  WHERE `id1` = 42')
//            ->getQuery()
////            ->getSingleScalarResult()
//            ;
//    }

}
