<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;


/**
 * TrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrackRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     * Nous donne le nombre de son(s) reliés au son visualisé
//     *
//     * @return mixed float | null
//     */
//    public function getNumberTracks()    // int $id)
//    {
//        $qb = $this->createQueryBuilder('t');
//
//        return $qb
//            ->select('COUNT(*) FROM `track`  WHERE `id1` = 42')
//            ->getQuery()
////            ->getSingleScalarResult()
//            ;
//    }


//    /**
//     * On veut afficher les Tracks par ordre décroissant de la date de création
//     * @return mixed float | null
//     * @throws \Doctrine\ORM\NoResultException
//     * @throws \Doctrine\ORM\NonUniqueResultException
//     */
//    public function getTrackByOrder()
//    {
//        $qb = $this->createQueryBuilder('u');
//
//        return $qb
//            ->select('FROM `track` ORDER By `creationDate` DESC')
//            ->getQuery()
//            ->getSingleScalarResult();

//$redCars = $carRepository->findBy( array ( 'color' => 'red' ), array ( 'creationDate' => 'ASC' ));


//    }

}
